### ISSUE TITLE
Import Error on Windows

### ISSUE THREAD

**Issue by arsenetar** [hsoft/send2trash#14]
Using python 3.5.3 on windows 10 (both 64bit). Version 1.3.1 works fine, version 1.4.0 throws an import exception.  Issue is in:  
```
File "C:\Users\arsen\github\dupeguru\env\lib\site-packages\send2trash\compat.py", line 14, in <module>
    environb = os.environb
AttributeError: module 'os' has no attribute 'environb'
```
Looks like this was introduced in https://github.com/hsoft/send2trash/commit/f324ff491ea9465126f01b510f169eac7ff65679

**Comment by hsoft** [comment]
oh... I didn't know that `environb` was not Windows-proof ( https://docs.python.org/3/library/os.html#os.supports_bytes_environ ). Will fix right away. Thanks for the heads up!

**Comment by hsoft** [comment]
@arsenetar does this commit referenced above fix the problem?

**Comment by arsenetar** [comment]
Cloned and installed in virtualenv.  Seems to be good now.

**Comment by hsoft** [comment]
Ok thanks, releasing v1.4.1 right away.
